### PR TITLE
Implement upgrade moving

### PR DESCRIPTION
**Pull request by Ennis0**
Added functionality to move upgrades between units simply and implemented the three unimplemented cards that relied on it.

### CODE REVIEW

**Comment by danbastin** [comment]
I'm able to steal upgrades even if I don't have enough to pay for them. Attaching the game state where Pre Viszla steals The Darksaber from Leader Sabine. Playing him out of aspect costs 9 putting me to 1/10 resources but I can still steal. 
[gamestate.txt](https://github.com/user-attachments/files/16163534/gamestate.txt)

**Comment by Ennis0** [comment]
Gotcha. I'll look into it.

**Comment by Ennis0** [comment]
I fixed the issue, and added Pre's on attack trigger which I missed before.

**Comment by danbastin** [comment]
Screenshot 2024-07-10 at 11 13 34 AM

You've tapped into some deep code haha. From the same game state this was when attacking with Pre. The Darksaber was on Leia. It also asked which ability I would like to activate on Pre as if he had an activated ability but only showed attack.

**Comment by Ennis0** [comment]
Well dang. I get no such problems, but I'm going to try recreating that gamestate and see if it happens for me.

**Comment by Ennis0** [comment]
Untitled
Works just fine for me. The issue might be in server/networking stuff rather than game logic. Did you recreate the game state in some special way(loading in from a file or something?) Did you refresh the page at any point?

**Comment by danbastin** [comment]
Yeah, let me know. I'll try recreating in a different game.

**Comment by danbastin** [comment]
Gonna go ahead and merge this since it either does or mostly works. We can handle individual issues as they come up.

**Pull request merged**
