### PR TITLE
feat: randomness improved

### PR DESCRIPTION
**Pull request by brubraz**
### Improved randomness when shuffling the deck

- Changed `mt_rand` to `random_int`.
`random_int` is better than `mt_rand` in PHP for higher randomness because it uses a cryptographic random number generator, providing stronger unpredictability. `mt_rand` uses the Mersenne Twister algorithm, which is not suitable for cryptographic purposes. Regarding seeds, `random_int` relies on sources like /dev/urandom or CryptGenRandom, ensuring better randomness without manual seeding.

### CODE REVIEW

**Comment by OotTheMonk** [comment]
Is it possible to manually seed the new function? The reason this all was done is because people were complaining about other people abusing undo to achieve a more desired random result (for example undo and redo a mulligan, or a random discard, or a die roll in FaB). This was written to make the result be deterministic if they undo then redo the same sequence of game actions.

**Comment by brubraz** [comment]
> Is it possible to manually seed the new function? The reason this all was done is because people were complaining about other people abusing undo to achieve a more desired random result (for example undo and redo a mulligan, or a random discard, or a die roll in FaB). This was written to make the result be deterministic if they undo then redo the same sequence of game actions while still being sufficiently unpredictable to be suitable for achieving card mixing.



> Is it possible to manually seed the new function? The reason this all was done is because people were complaining about other people abusing undo to achieve a more desired random result (for example undo and redo a mulligan, or a random discard, or a die roll in FaB). This was written to make the result be deterministic if they undo then redo the same sequence of game actions while still being sufficiently unpredictable to be suitable for achieving card mixing.

I see your point. What do you think if we shuffle the deck at the initial state using the `random_int`? Then, we could use the `mt_rand` with seed to keep the same sequence if they undo.

**Comment by OotTheMonk** [comment]
I think there's a very subtle bug here; the problem is that randomSeeded is true both on the initial shuffle, and also for all calls to GetRandom after the first one while processing the same gamestate. So it would only respect the undo invariance if no more than one random effect is done during that gamestate processing.

**Comment by brubraz** [comment]
> I think there's a very subtle bug here; the problem is that randomSeeded is true both on the initial shuffle, and also for all calls to GetRandom after the first one while processing the same gamestate. So it would only respect the undo invariance if no more than one random effect is done during that gamestate processing.

I got your point and I updated the code to use `random_int` only on the initial shuffle.

**Pull request merged**
